language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - nurfeeza@hotmail.com
    on_success: always
    on_failure: always
branches:
  only:
   - development

before_script:
  - npm install -g @angular/cli
  - npm install -g now
  
script:
  - ng lint
  - ng build --prod --base-href https://hafxxza.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0cc83d21676f3d3904ca706e3c616b30089c63a2
  local_dir: dist/bitcoin
  edge: true
  on: 
   branch: development 

